server:
  port: 8091
spring:
  application:
    name: websocket-demo
  thymeleaf:
    prefix: classpath:/static/html/
  # 数据库配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/zhangqianwen?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhangqianwen123
    # 使用druid数据源
    #          type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

    #      spring.datasource.url=jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    #      spring.datasource.username=root
    #      spring.datasource.password=root
    #      spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 192.168.1.235
    port: 6379
    password: 123456
    timeout: 5000

# mybatis 配置
mybatis:
  mapperLocations: mapper/*.xml
  typeAliasesPackage: com.gj.business.mapper.*
    # redis配置
    # Redis数据库索引（默认为0）
#Redis:
##    database: 0
#      # Redis服务器地址
#  host: 192.168.1.235
#      # Redis服务器连接端口
#    port: 6379
#      # Redis服务器连接密码（默认为空）
#    password: 123456
#      # 连接池最大连接数（使用负值表示没有限制）
#    pool:
#      max-active: 200
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 10
#      # 连接池中的最小空闲连接
#      min-idle: 0
#    # 连接超时时间（毫秒）
#    timeout: 1000

